version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.config.celery_config.celery_app worker --loglevel=info --include=src.services.processing_tasks
    depends_on:
      - fastapi

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.config.celery_config.celery_app beat --loglevel=info
    depends_on:
      - fastapi
